### ISSUE TITLE
Following run instruction produces error

### ISSUE THREAD

**Issue by NikVolf** [mixbytes/tank.bench-polkadot#4]
`$ node dist/index.js`

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/nikolayvolf/git/tank.bench-polkadot/node_modules/tank.bench-common/dist/lib/worker/WorkersWrapper.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by NikVolf** [comment]
Probably outdated node :)
